replicaCount: 1

frontend:
  image: mavrick1/kubestellar-f:latest
  port: 80

backend:
  image: mavrick1/kubestellar-b:latest
  port: 4000

redis:
  image: "redis:latest"
  port: 6379

kubeConfig: ""
