apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig-secret
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /root/.kube
              subPath: config
          env:
            - name: KUBECONFIG
              value: "/root/.kube/config"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
